# Repository settings managed by the Settings app
# This file will be applied when the Settings app is installed and enabled

repository:
  # Repository basics
  name: F.R.I.D.A.Y
  description: "F.R.I.D.A.Y - An intelligent assistant system"
  homepage: ""
  topics: ["ai", "assistant", "python", "automation"]
  
  # Repository settings
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  
  # Repository features
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  
  # Repository security
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        bypass_pull_request_allowances:
          users: []
          teams: []
          apps: []
      
      # Required status checks
      required_status_checks:
        strict: true
        contexts:
          - build
          - coverage
          - sonar
          - trivy
      
      # Other protections
      enforce_admins: false
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      
      # Required signatures
      required_signatures: true
      
      # Restrictions (who can push)
      restrictions:
        users: []
        teams: []
        apps: []

# Labels for the repository
labels:
  # Type labels
  - name: bug
    color: "d73a4a"
    description: "Something isn't working"
  
  - name: feature
    color: "a2eeef"
    description: "New feature or request"
  
  - name: enhancement
    color: "84b6eb"
    description: "Improvement to existing feature"
  
  - name: documentation
    color: "0075ca"
    description: "Improvements or additions to documentation"
  
  - name: security
    color: "b60205"
    description: "Security-related issue or improvement"
    
  # Priority labels
  - name: priority-critical
    color: "b60205"
    description: "Critical priority"
  
  - name: priority-high
    color: "d93f0b"
    description: "High priority"
  
  - name: priority-medium
    color: "fbca04"
    description: "Medium priority"
  
  - name: priority-low
    color: "0e8a16"
    description: "Low priority"
  
  # Status labels
  - name: needs-triage
    color: "ededed"
    description: "Needs initial triage"
  
  - name: approved
    color: "0e8a16"
    description: "Approved for merge"
  
  - name: dependencies
    color: "0366d6"
    description: "Dependency updates"
  
  - name: chore
    color: "ededed"
    description: "Maintenance or housekeeping"
  
  # Area labels
  - name: frontend
    color: "c2e0c6"
    description: "Frontend related"
    
  - name: backend
    color: "fef2c0"
    description: "Backend related"
  
  - name: ci
    color: "1d76db"
    description: "Continuous Integration"
  
  - name: tests
    color: "bfd4f2"
    description: "Testing related"

# Collaborators and teams (optional - can be managed separately)
# collaborators: []
# teams: []