coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 70%
        threshold: 1%
        informational: true

comment:
  layout: "diff"
  behavior: default
  require_changes: false