name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'  # Run weekly on Monday at 6AM UTC

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    # Optional: Scan Docker images if Dockerfile exists
    - name: Check for Dockerfile
      id: docker_check
      run: |
        if [ -f Dockerfile ]; then
          echo "dockerfile_exists=true" >> $GITHUB_OUTPUT
        else
          echo "dockerfile_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Build Docker image for scanning
      if: steps.docker_check.outputs.dockerfile_exists == 'true'
      run: docker build -t friday-app:latest .

    - name: Run Trivy Docker image scan
      if: steps.docker_check.outputs.dockerfile_exists == 'true'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'friday-app:latest'
        format: 'sarif'
        output: 'trivy-docker-results.sarif'

    - name: Upload Docker scan results to GitHub Security tab
      if: steps.docker_check.outputs.dockerfile_exists == 'true'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-docker-results.sarif'